[book]
title = "ontoparse"
authors = ["Parker Hicks"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/phicks22/ontoparse"
search.use-boolean-and = true

[preprocessor.toc]
command = "mdbook-toc"
